let gallery=[],visible=[],active=0,stock=[];
const $=id=>document.getElementById(id), box=$('lightbox');
function show(i){active=(i+visible.length)%visible.length;const item=visible[active];$('large').src=item.src;$('large').alt=item.title;$('caption').textContent=item.provenance+' — '+item.title;if(!box.open)box.showModal()}
function photos(group){visible=gallery.filter(i=>group==='all'||i.group===group);$('photos').replaceChildren();visible.forEach((item,i)=>{const f=document.createElement('figure');f.className='photo';const b=document.createElement('button');b.setAttribute('aria-label','Enlarge '+item.title);const img=document.createElement('img');img.src=item.src;img.alt=item.title;img.loading='lazy';b.append(img);b.onclick=()=>{visible=gallery.filter(x=>group==='all'||x.group===group);show(i)};const cap=document.createElement('figcaption');const tag=document.createElement('span');tag.className='provenance';tag.textContent=item.provenance;cap.append(tag,document.createTextNode(item.title));f.append(b,cap);$('photos').append(f)});$('galleryCount').textContent=visible.length+' images';document.querySelectorAll('[data-group]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.group===group))}
function refs(){const q=$('search').value.toLowerCase(),mode=$('filter').value;const rows=stock.filter(r=>(mode==='all'||mode==='short'&&r.shortlist||mode==='vertical'&&r.orientation==='vertical')&&JSON.stringify(r).toLowerCase().includes(q));$('refs').replaceChildren();rows.forEach(r=>{const a=document.createElement('a');a.href=r.source_url;a.target='_blank';a.rel='noopener noreferrer';a.className='reference';const id=document.createElement('span');id.className='id';id.textContent='STOCK REFERENCE / '+r.id+' / '+r.orientation;const h=document.createElement('h3');h.textContent=r.species_group+' sea lion ↗';const p=document.createElement('p');p.textContent=r.study_note||r.location||'Underwater movement reference';const credit=document.createElement('small');credit.textContent=r.photographer+' · '+r.agency;const img=document.createElement('img');img.src=r.preview_url;img.alt=r.species_group+' sea lion — '+r.photographer;img.loading='lazy';img.referrerPolicy='no-referrer';img.className='stock-preview';img.onerror=()=>{img.remove();const unavailable=document.createElement('p');unavailable.textContent='Preview unavailable · view at source ↗';a.prepend(unavailable)};a.append(img,id,h,p,credit);$('refs').append(a)});$('refCount').textContent=rows.length+' references'+(rows.length?'':' — try another search')}
$('close').onclick=()=>box.close();$('prev').onclick=()=>show(active-1);$('next').onclick=()=>show(active+1);box.addEventListener('click',e=>{if(e.target===box)box.close()});box.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(active+1);if(e.key==='ArrowLeft')show(active-1)});document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>photos(b.dataset.group));$('search').oninput=refs;$('filter').onchange=refs;
Promise.all([fetch('gallery.json').then(r=>r.json()),fetch('references.json').then(r=>r.json())]).then(([g,s])=>{gallery=g;stock=s;photos('all');mine();concepts();refs();const art=g.find(i=>i.group==='art');const b=document.createElement('button');b.setAttribute('aria-label','Enlarge sea lion artwork');const img=document.createElement('img');img.src=art.src;img.alt=art.title;b.append(img);b.onclick=()=>{photos('art');show(0)};$('heroArt').append(b)}).catch(()=>{$('galleryCount').textContent='The gallery could not load. Please reload the page.'});

function mine(){const own=gallery.filter(i=>i.provenance==='My photos').sort((a,b)=>Number(b.title.startsWith('Sea lion'))-Number(a.title.startsWith('Sea lion')));own.forEach(item=>{const f=document.createElement('figure');f.className='photo';const b=document.createElement('button');b.setAttribute('aria-label','Enlarge '+item.title);const img=document.createElement('img');img.src=item.src;img.alt=item.title;img.loading='lazy';b.append(img);b.onclick=()=>{visible=own;show(own.indexOf(item))};const cap=document.createElement('figcaption');cap.textContent='My photos — '+item.title;f.append(b,cap);$('mine').append(f)})}

function concepts(){const items=gallery.filter(x=>x.group==='study');items.forEach(item=>{const f=document.createElement('figure');f.className='photo';const b=document.createElement('button');b.setAttribute('aria-label','Enlarge '+item.title);const img=document.createElement('img');img.src=item.src;img.alt=item.title;img.loading='lazy';b.append(img);b.onclick=()=>{visible=items;show(items.indexOf(item))};const cap=document.createElement('figcaption');const tag=document.createElement('span');tag.className='provenance';tag.textContent=item.provenance;cap.append(tag,document.createTextNode(item.title));f.append(b,cap);$('conceptPhotos').append(f)})}
